title: Blog de WeirdSignal
description: Mes articles autour du projet Meshtastic
baseurl: ""
url: "https://weirdsignal.github.io"

# remote_theme: pages-themes/cayman@v0.2.0
remote_theme: pages-themes/midnight@v0.2.0
 
plugins:
  - jekyll-plantuml
  - jekyll-remote-theme

exclude:
  - README.md
