title: Mon Blog
description: Un blog personnel hébergé sur GitHub Pages
baseurl: ""
url: "https://weirdsignal.github.io"

# theme: minima
theme: cayman


plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
