title: Mon Blog
description: Un blog personnel hébergé sur GitHub Pages
baseurl: ""
url: "https://weirdsignal.github.io"
remote_theme: pages-themes/minimal
plugins:
  - jekyll-feed
  - jekyll-seo-tag
