title: Mon Blog
description: Un blog personnel hébergé sur GitHub Pages
baseurl: ""
url: "https://weirdsignal.github.io"

remote_theme: pages-themes/cayman@v0.2.0

# Midnight ne s'applique sur sur la page d'acceuil
# remote_theme: pages-themes/midnight@v0.2.0
 
plugins:
  - jekyll-plantuml
  - jekyll-remote-theme

exclude:
  - README.md
