title: Mon Blog
description: Un blog personnel hébergé sur GitHub Pages
baseurl: ""
url: "https://weirdsignal.github.io"
# remote_theme: pages-themes/minimal
remote_theme: pages-themes/cayman

# theme: cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

exclude:
  - vendor/
  - README.md
